name: Build Hyggshi OS Code Mini

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f "Hyggshi OS Code Mini/requirements.txt" ]; then pip install -r "Hyggshi OS Code Mini/requirements.txt"; fi

    - name: List files before build (debug)
      run: ls -R "Hyggshi OS Code Mini"

    - name: Build executable on Windows
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        pyinstaller --onefile 'Hyggshi OS Code Mini\HyggshiOSCodeMini.py' --distpath 'Hyggshi OS Code Mini\build_dist'

    - name: Build executable on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        pyinstaller --onefile "Hyggshi OS Code Mini/HyggshiOSCodeMini.py" --distpath "Hyggshi OS Code Mini/build_dist"

    - name: List build folder (debug)
      run: ls -R "Hyggshi OS Code Mini/build_dist"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HyggshiOSCodeMini-${{ runner.os }}
        path: "Hyggshi OS Code Mini/build_dist/*"
