name: Build Hyggshi OS Code Mini

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    defaults:
      run:
        working-directory: "Hyggshi OS Code Mini"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: List files before build (debug)
      run: ls -R

    - name: Build executable
      shell: bash
      run: |
        pyinstaller --onefile --distpath build_dist HyggshiOSCodeMini.py

    - name: List build folder (debug)
      run: ls -R build_dist

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HyggshiOSCodeMini-${{ matrix.os }}
        path: build_dist/*
